env:
  CARGO_INCREMENTAL: '0'
  CARGO_NET_RETRY: '10'
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: '1'
  RUSTDOCFLAGS: -D warnings
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: '10'

linux_task:
  name: test (aarch64-unknown-linux-gnu)
  env:
    TARGET: aarch64-unknown-linux-gnu
  arm_container:
    image: rust:latest
  setup_script:
    - rustup toolchain add nightly && rustup default nightly
  test_script:
    - cargo test --all --all-features --exclude benchmarks -- --test-threads=1
    - cargo test --all --all-features --exclude benchmarks --release -- --test-threads=1

macos_task:
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-xcode:latest
  matrix:
    - name: test (aarch64-apple-darwin)
      env:
        TARGET: aarch64-apple-darwin
    - name: test (x86_64-apple-darwin)
      env:
        TARGET: x86_64-apple-darwin
  setup_script:
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain nightly
    - source $HOME/.cargo/env
    - rustup toolchain add nightly-$TARGET && rustup default nightly-$TARGET
  test_script:
    - source $HOME/.cargo/env
    - cargo test --all --all-features --exclude benchmarks -- --test-threads=1
    - cargo test --all --all-features --exclude benchmarks --release -- --test-threads=1
